server:
  port: 8080

database:
  host: localhost
  port: 5432
  username: postgres
  password: postgres
  name: postgres
  sslmode: disable

logging:
  level: ERROR

redis:
  host: localhost
  password: password
  port: 6379

# OS ENV
app_env: development