server:
  port: 8080

database:
  host: host.docker.internal # localhost
  port: 5432
  username: postgres
  password: postgres
  name: postgres
  sslmode: disable

logging:
  level: INFO

redis:
  host: host.docker.internal # localhost
  password: password
  port: 6379

# OS ENV
app_env: development