apiVersion: v1
kind: Service
metadata:
  name: go-service
  namespace: go-app
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30006
  selector:
    app: go-deployment # ref by spec.template