version: '3.9'

services:
  postgres:
    image: postgres
    container_name: postgres_cn
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - './data:/var/lib/postgres'

  redis:
    image: redis
    container_name: redis_cn
    command: redis-server /redis.conf --requirepass password
    ports:
      - '6379:6379'
    volumes:
      - ./data/redis:/data
